"""empty message

Revision ID: d8c37db5302f
Revises: 
Create Date: 2019-07-09 18:51:42.156280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c37db5302f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('reg_no2', sa.String(length=500), nullable=True))
    op.add_column('proposal', sa.Column('student1', sa.String(length=100), nullable=True))
    op.add_column('proposal', sa.Column('student2', sa.String(length=500), nullable=True))
    op.drop_column('proposal', 'student_pair')
    op.add_column('users', sa.Column('email2', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('reg_no2', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('student1', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('student2', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('tel', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('tel2', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tel2')
    op.drop_column('users', 'tel')
    op.drop_column('users', 'student2')
    op.drop_column('users', 'student1')
    op.drop_column('users', 'reg_no2')
    op.drop_column('users', 'email2')
    op.add_column('proposal', sa.Column('student_pair', sa.VARCHAR(length=500), nullable=True))
    op.drop_column('proposal', 'student2')
    op.drop_column('proposal', 'student1')
    op.drop_column('proposal', 'reg_no2')
    # ### end Alembic commands ###
